/**
 * Student Planner Service
 * Provides data management, local persistence, and AI Daily Motivation generation
 */

export interface ExamTarget {
  title: string;
  targetDate: string; // ISO string or YYYY-MM-DDTHH:mm
}

export interface HomeworkTask {
  id: string;
  title: string;
  subject: string;
  dueDate?: string;
  completed: boolean;
  priority: 'rendah' | 'sederhana' | 'tinggi';
  createdAt: string;
}

export interface ScheduleBlock {
  id: string;
  day: string; // 'Isnin' | 'Selasa' | 'Rabu' | 'Khamis' | 'Jumaat' | 'Sabtu' | 'Ahad'
  startTime: string; // '08:00'
  endTime: string;   // '09:30'
  subject: string;
  title: string;
  color: string; // tailwind color token
}

export interface DailyMotivation {
  quote: string;
  author: string;
  category: string;
  dateKey: string;
}

const STORAGE_KEYS = {
  EXAM_TARGET: 'study_dermaa_planner_exam_target',
  HOMEWORK_TASKS: 'study_dermaa_planner_homework_tasks',
  STUDY_SCHEDULE: 'study_dermaa_planner_study_schedule',
  POMODORO_STATS: 'study_dermaa_planner_pomodoro_stats',
  DAILY_QUOTE: 'study_dermaa_planner_daily_quote',
};

// ==========================================
// 1. DAILY MOTIVATION (AI GENERATION)
// ==========================================

/**
 * Exact hidden prompt logic to generate a short, modern quote about positive learning culture,
 * explicitly instructing the AI never to mention it is an AI or generated by AI.
 */
export const DAILY_MOTIVATION_HIDDEN_PROMPT = {
  systemInstruction:
    'You are a wise, forward-thinking academic mentor fostering a positive learning culture for Malaysian students (KSSM/SPM). ' +
    'Craft a short, modern, deeply inspiring motivational quote (1-2 sentences maximum) centered on positive learning culture, ' +
    'growth mindset, relentless curiosity, grit, and the joy of daily improvement. ' +
    'The quote can be in modern Bahasa Melayu or inspiring bilingual phrasing.\n\n' +
    'CRITICAL STRICT CONSTRAINTS:\n' +
    '1. NEVER state, hint, or acknowledge that you are an AI, a machine learning model, or a virtual assistant.\n' +
    '2. NEVER use phrases like "As an AI", "Here is your quote", "Generated by AI", "I hope this motivates you", or any robotic preamble.\n' +
    '3. Output ONLY the quote followed by the attribution in this exact single-line format:\n' +
    '"[The Quote Text]" — [Attribution/Theme Name]\n' +
    'Example:\n' +
    '"Kejayaan bukan tentang kepintaran semalaman, tetapi keberanian untuk belajar daripada kesilapan setiap hari." — Budaya Belajar Positif',
  userPrompt:
    'Sila berikan satu mutiara kata harian yang segar, bertenaga, dan mencetuskan inspirasi budaya pembelajaran positif untuk pelajar hari ini.',
};

/**
 * High-quality curated quotes as instant fallback when offline or during transient spikes
 */
const FALLBACK_MOTIVATIONAL_QUOTES: Array<{ quote: string; author: string; category: string }> = [
  {
    quote: 'Kejayaan bukan tentang kepintaran semalaman, tetapi keberanian untuk bangkit dan belajar semula daripada setiap kesilapan.',
    author: 'Budaya Belajar Positif',
    category: 'Ketabahan',
  },
  {
    quote: 'Setiap minit fokus yang anda laburkan hari ini adalah jambatan menuju keyakinan di dewan peperiksaan esok.',
    author: 'Inspirasi study.dermaa',
    category: 'Fokus',
  },
  {
    quote: 'Disiplin kecil yang diulang setiap hari menghasilkan pencapaian luar biasa yang tidak disangka.',
    author: 'Minda Berkembang',
    category: 'Disiplin',
  },
  {
    quote: 'Jangan takut soalan yang sukar; di situlah pemahaman sebenar anda sedang diasah menjadi permata.',
    author: 'Semangat Inkuiri KSSM',
    category: 'Cabaran',
  },
  {
    quote: 'Belajar bukan sekadar untuk lulus peperiksaan, tetapi untuk membina keupayaan berfikir dan mengubah masa depan.',
    author: 'Falsafah Pendidikan Dermaa',
    category: 'Visi',
  },
  {
    quote: 'Konsistensi 25 minit belajar yang berkualiti jauh lebih bernilai daripada berjam-jam tanpa arah tuju.',
    author: 'Teknik Belajar Berkesan',
    category: 'Produktiviti',
  },
];

/**
 * Fetches or retrieves the daily motivational quote with the hidden prompt logic.
 * Employs local caching by date to prevent redundant API calls while offering force-refresh.
 */
export async function fetchDailyMotivationQuote(forceRefresh: boolean = false): Promise<DailyMotivation> {
  const todayKey = new Date().toISOString().split('T')[0];

  // 1. Check local cache first unless force refresh requested
  if (!forceRefresh) {
    try {
      const cachedRaw = localStorage.getItem(STORAGE_KEYS.DAILY_QUOTE);
      if (cachedRaw) {
        const cached: DailyMotivation = JSON.parse(cachedRaw);
        if (cached && cached.dateKey === todayKey && cached.quote) {
          return cached;
        }
      }
    } catch {
      // Ignore cache parse errors
    }
  }

  // 2. Fetch fresh quote via server-side Gemini API proxy (/api/gemini/chat)
  try {
    const response = await fetch('/api/gemini/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages: [
          {
            role: 'user',
            parts: [{ text: DAILY_MOTIVATION_HIDDEN_PROMPT.userPrompt }],
          },
        ],
        systemInstruction: DAILY_MOTIVATION_HIDDEN_PROMPT.systemInstruction,
        model: 'gemini-3.8-flash',
      }),
    });

    if (response.ok) {
      const data = await response.json();
      const rawText = data?.reply || '';

      if (rawText && typeof rawText === 'string') {
        // Parse the quote and attribution
        let quote = rawText.trim();
        let author = 'Budaya Belajar Positif';

        // Check for delimiter like "—" or "-" or attribution
        const dashIdx = quote.lastIndexOf('—');
        const altDashIdx = quote.lastIndexOf(' - ');

        if (dashIdx !== -1) {
          author = quote.substring(dashIdx + 1).trim();
          quote = quote.substring(0, dashIdx).trim();
        } else if (altDashIdx !== -1) {
          author = quote.substring(altDashIdx + 3).trim();
          quote = quote.substring(0, altDashIdx).trim();
        }

        // Clean quotes wrapping
        quote = quote.replace(/^["'“]/, '').replace(/["'”]$/, '').trim();
        author = author.replace(/^["'“]/, '').replace(/["'”]$/, '').trim();

        // Enforce anti-AI leaks if any model hallucinated
        quote = quote.replace(/as an AI|artificial intelligence|language model|saya sebagai AI/gi, '').trim();

        if (quote.length > 10) {
          const result: DailyMotivation = {
            quote,
            author: author || 'Budaya Belajar Positif',
            category: 'Inspirasi Harian',
            dateKey: todayKey,
          };
          localStorage.setItem(STORAGE_KEYS.DAILY_QUOTE, JSON.stringify(result));
          return result;
        }
      }
    }
  } catch (err) {
    console.warn('AI Quote request encountered network/proxy delay, using curated inspiration:', err);
  }

  // 3. Fallback deterministic selection based on day of month
  const dayOfMonth = new Date().getDate();
  const selectedFallback = FALLBACK_MOTIVATIONAL_QUOTES[dayOfMonth % FALLBACK_MOTIVATIONAL_QUOTES.length];

  const fallbackResult: DailyMotivation = {
    ...selectedFallback,
    dateKey: todayKey,
  };

  try {
    localStorage.setItem(STORAGE_KEYS.DAILY_QUOTE, JSON.stringify(fallbackResult));
  } catch {
    // Ignore storage quota
  }

  return fallbackResult;
}

// ==========================================
// 2. EXAM TARGET PERSISTENCE
// ==========================================

export function getStoredExamTarget(): ExamTarget {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.EXAM_TARGET);
    if (raw) {
      return JSON.parse(raw);
    }
  } catch {
    // Ignore
  }

  // Default target: SPM 2026 examination (approximated early November)
  const defaultDate = new Date();
  defaultDate.setMonth(defaultDate.getMonth() + 2);
  defaultDate.setHours(8, 0, 0, 0);

  return {
    title: 'Peperiksaan SPM 2026',
    targetDate: defaultDate.toISOString().slice(0, 16),
  };
}

export function saveStoredExamTarget(target: ExamTarget): void {
  try {
    localStorage.setItem(STORAGE_KEYS.EXAM_TARGET, JSON.stringify(target));
  } catch (err) {
    console.error('Failed to save exam target:', err);
  }
}

// ==========================================
// 3. HOMEWORK TASKS PERSISTENCE
// ==========================================

const DEFAULT_HOMEWORK_TASKS: HomeworkTask[] = [
  {
    id: 'hw-1',
    title: 'Latihan Matematik Tingkatan 4 (Bab 3: Penaakulan Logik)',
    subject: 'Matematik',
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString().slice(0, 10),
    completed: false,
    priority: 'tinggi',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hw-2',
    title: 'Ulangkaji Nota Sains DLP: Cell as the Basic Unit of Life',
    subject: 'Sains (DLP)',
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString().slice(0, 10),
    completed: false,
    priority: 'sederhana',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'hw-3',
    title: 'Siapkan Esei Sejarah KSSM (Bab 2: Kebangkitan Nasionalisme)',
    subject: 'Sejarah',
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString().slice(0, 10),
    completed: true,
    priority: 'sederhana',
    createdAt: new Date().toISOString(),
  },
];

export function getStoredHomeworkTasks(): HomeworkTask[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.HOMEWORK_TASKS);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch {
    // Ignore
  }
  return DEFAULT_HOMEWORK_TASKS;
}

export function saveStoredHomeworkTasks(tasks: HomeworkTask[]): void {
  try {
    localStorage.setItem(STORAGE_KEYS.HOMEWORK_TASKS, JSON.stringify(tasks));
  } catch (err) {
    console.error('Failed to save homework tasks:', err);
  }
}

// ==========================================
// 4. STUDY SCHEDULE TIME-BLOCKS PERSISTENCE
// ==========================================

export const DEFAULT_SCHEDULE_DAYS = ['Isnin', 'Selasa', 'Rabu', 'Khamis', 'Jumaat', 'Sabtu', 'Ahad'] as const;

const DEFAULT_SCHEDULE_BLOCKS: ScheduleBlock[] = [
  {
    id: 'sb-1',
    day: 'Isnin',
    startTime: '08:00',
    endTime: '09:30',
    subject: 'Matematik',
    title: 'Pengukuhan Formula & Pengiraan Latihan',
    color: 'emerald',
  },
  {
    id: 'sb-2',
    day: 'Isnin',
    startTime: '10:00',
    endTime: '11:30',
    subject: 'Sains',
    title: 'Eksperimen & Konsep Asas Sains DLP',
    color: 'teal',
  },
  {
    id: 'sb-3',
    day: 'Isnin',
    startTime: '14:30',
    endTime: '16:00',
    subject: 'Sejarah',
    title: 'Peta Minda Bab Penting & Kronologi',
    color: 'amber',
  },
  {
    id: 'sb-4',
    day: 'Isnin',
    startTime: '20:30',
    endTime: '22:00',
    subject: 'Bahasa Melayu',
    title: 'Latihan Karangan & Tatabahasa SPM',
    color: 'sky',
  },
  // Selasa
  {
    id: 'sb-5',
    day: 'Selasa',
    startTime: '08:30',
    endTime: '10:00',
    subject: 'Bahasa Inggeris',
    title: 'Reading Comprehension & Grammar Drill',
    color: 'indigo',
  },
  {
    id: 'sb-6',
    day: 'Selasa',
    startTime: '14:00',
    endTime: '15:30',
    subject: 'Matematik Tambahan',
    title: 'Fungsi Kuadratik & Kalkulus Asas',
    color: 'emerald',
  },
  {
    id: 'sb-7',
    day: 'Selasa',
    startTime: '20:00',
    endTime: '21:30',
    subject: 'Kuiz Kendiri',
    title: 'Ujian Percubaan Topikal 15 Soalan',
    color: 'rose',
  },
  // Rabu
  {
    id: 'sb-8',
    day: 'Rabu',
    startTime: '09:00',
    endTime: '10:30',
    subject: 'Pendidikan Islam / Moral',
    title: 'Hafazan Ayat Kefahaman & Nilai Murni',
    color: 'emerald',
  },
  {
    id: 'sb-9',
    day: 'Rabu',
    startTime: '15:00',
    endTime: '16:30',
    subject: 'Fizik / Kimia',
    title: 'Ulangkaji Teori Daya & Ikatan Kimia',
    color: 'teal',
  },
  {
    id: 'sb-10',
    day: 'Rabu',
    startTime: '20:30',
    endTime: '22:00',
    subject: 'Kerja Rumah',
    title: 'Menyiapkan Tugasan Tertunggak',
    color: 'amber',
  },
];

export function getStoredScheduleBlocks(): ScheduleBlock[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.STUDY_SCHEDULE);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch {
    // Ignore
  }
  return DEFAULT_SCHEDULE_BLOCKS;
}

export function saveStoredScheduleBlocks(blocks: ScheduleBlock[]): void {
  try {
    localStorage.setItem(STORAGE_KEYS.STUDY_SCHEDULE, JSON.stringify(blocks));
  } catch (err) {
    console.error('Failed to save study schedule:', err);
  }
}

// ==========================================
// 5. POMODORO SESSION STATS
// ==========================================

export interface PomodoroTodayStats {
  date: string;
  focusSessionsCompleted: number;
  totalFocusMinutes: number;
}

export function getStoredPomodoroStats(): PomodoroTodayStats {
  const today = new Date().toISOString().split('T')[0];
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.POMODORO_STATS);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed.date === today) {
        return parsed;
      }
    }
  } catch {
    // Ignore
  }
  return {
    date: today,
    focusSessionsCompleted: 0,
    totalFocusMinutes: 0,
  };
}

export function incrementPomodoroSession(minutes: number = 25): PomodoroTodayStats {
  const current = getStoredPomodoroStats();
  const updated: PomodoroTodayStats = {
    date: current.date,
    focusSessionsCompleted: current.focusSessionsCompleted + 1,
    totalFocusMinutes: current.totalFocusMinutes + minutes,
  };
  try {
    localStorage.setItem(STORAGE_KEYS.POMODORO_STATS, JSON.stringify(updated));
  } catch {
    // Ignore
  }
  return updated;
}
